---
- name: prepare hosts
  hosts: all
  remote_user: ubuntu
  vars:
    zuul_user: zuul
    zuul_host: zuul.scs.community
    webhook_token: webhooksecretvalue  # set me from command line
    db_user_pass: userpassword         # set me from command line
    db_root_pass: rootpassword         # set me from command line
  pre_tasks:
    - name: update all packages
      ansible.builtin.apt:
        update_cache: true
        name: '*'
        state: latest
      become: true

    - name: install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - docker.io
          - docker-compose
          - python3-docker
      become: true
    
    - name: add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: true
      become: true

    - name: add group
      group:
        name: "{{ zuul_user }}"
      become: true

    - name: add user
      user:
        name: "{{ zuul_user }}"
        shell: /bin/bash
        group: "{{ zuul_user }}"
        groups: sudo
        append: true
        home: "/home/{{ zuul_user }}"
      become: true

  roles:
    - name: zuul-setup role
      role: zuul-ci
      vars:
        operator_user: "{{ zuul_user }}"
        zookeeper_fqdn: zookeeper_1.scs
        connections:
          scszuulapp:
            driver: github
            webhook_token: "{{ webhook_token }}"
            app_id: 124290
            app_key: "/etc/zuul/pem-files/scszuulapp.pem"
          opendevorg:
            name: opendev
            driver: git
            baseurl: https://opendev.org
        tenants:
          - tenant:
              name: SovereignCloudStack
              source:
                opendevorg:
                  untrusted-projects:
                    - zuul/zuul-jobs:
                        include:
                          - job
                scszuulapp:
                  config-projects:
                    - SovereignCloudStack/zuul_config:
                        load-branch: main
                  untrusted-projects:
                    - SovereignCloudStack/github-permissions
                    - SovereignCloudStack/zuul-sandbox
        database:
          user_name: zuul
          user_pass: "{{ db_user_pass }}"
          root_pass: "{{ db_root_pass }}"
          db_name: zuul
        container_name:
          mariadb: "zuul_mariadb"
          zookeeper: "zuul_zookeeper"
          nodepool_launcher: "zuul_nodepool_launcher"
          zuul_scheduler: "zuul_scheduler"
          zuul_web: "zuul_web"
          zuul_executor: "zuul_executor"
          log_server: "zuul_log_server"
          worker_node_list:
            - "zuul_worker_node_1"
            - "zuul_worker_node_2"
            - "zuul_worker_node_3"
        nodepool_providers:
          providers:  # we need this sub-key. limitation of to_nice_yaml library
            - name: static-vms
              driver: static
              pools:
                - name: main
                  nodes:
                    - name: zuul_worker_node_1
                      labels: ubuntu-focal  # make sure nodepool_labels has this
                      host-key-checking: false
                      python-path: /usr/bin/python3
                      username: root
                    - name: zuul_worker_node_2
                      labels: ubuntu-focal  # make sure nodepool_labels has this
                      host-key-checking: false
                      python-path: /usr/bin/python3
                      username: root
                    - name: zuul_worker_node_3
                      labels: ubuntu-focal  # make sure nodepool_labels has this
                      host-key-checking: false
                      python-path: /usr/bin/python3
                      username: root
      become: true
